[package]
name = "day-2"
version = "0.1.0"
edition = "2021"

[dependencies]
divan.workspace = true
itertools = "0.13.0"

[dev-dependencies]
itertools.workspace = true

[[bench]]
name = "day-2-bench"
path = "benches/benchmarks.rs"
harness = false
