[package]
name = "day-3"
version = "0.1.0"
edition = "2021"

[dependencies]
divan.workspace = true
itertools = "0.13.0"
regex = "1.9.5"
nom = "7.1.3"

[dev-dependencies]
itertools.workspace = true

[[bench]]
name = "day-3-bench"
path = "benches/benchmarks.rs"
harness = false
